import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="min-h-screen">
          <nav>
            <h1>CM</h1>
            <ul>
              <li></li>
            </ul>
          </nav>
        </section>
      </main>
    </div>
  );
}
